### ISSUE TITLE
Phase 4: Modify search algorithm to perform a search for all words as an additional option to the literal string search supported previously.

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#16]
Modify search algorithm to perform a search for all words as an additional option to the literal string search supported previously.
When the "contains all words or numbers" option is unchecked, a search for "this that" would search for the literal "this that". When the "contains all words or numbers" option is checked, a search for "this that" would search for labels that contain both the words "this" and "that" in any order.

**Comment by Conal-Tuohy** [comment]
done in revision 819391e1b80f5ba8cbc71560de5932b9481509e7

NB the search will match an edge in the graph if the labels of both the edge's nodes (taken together) match the search text. For example if an agency node contains the word "Police" and a related series contains the word "Photographs", then the two nodes will successfully match a search for "police photo".

NB the "contains all words" search is now the default.
