### ISSUE TITLE
Possible confusion with w3c PROV

### ISSUE THREAD

**Issue by beredim** [Conal-Tuohy/PROV-RIF-SPARQL#18]
There exists a w3c family of documents called PROV, dealing with provenance.
https://www.w3.org/TR/prov-overview/

As this is on a similar domain (linked data) using the same acronym, although derived differently, could lead to some confusion.

**Comment by Conal-Tuohy** [comment]
I have left a clarifying note in the README.md file.

Incidentally, in a later version of this software, I do actually expect to add PROV-O-encoded information describing the OAI-PMH harvest and cross-walk from RIF-CS format to CIDOC-CRM RDF, so the use of "PROV" would then become relevant for people looking for PROV-O.
