### ISSUE TITLE
Not all Agency date details appearing in node labels.

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#7]
As requested creating separate issues for any bugs I'm beginning to see, such as this one

**Comment by Conal-Tuohy** [comment]
Can you give an example? 

I am aware that there are some missing dates in the RIF-CS. Instead of "ND" the `startDate` or `endDate` element is simply omitted. Again this is something that will have to be addressed "upstream" (i.e. it has been fed into PROV's OAI-PMH repository that way).

**Comment by asaletourneau** [comment]
Sorry Conal, I mean't  toi include this image of VA475 where the date appears in the older version label but not in the new version label.
![no label date](https://cloud.githubusercontent.com/assets/1021209/12433682/a3c7d512-bf56-11e5-931b-490de79301be.jpg)

**Comment by Conal-Tuohy** [comment]
Needs revision to the SPARQL queries to concatenate the agency names with their dates of existence. Probably only 30 min work?

**Comment by asaletourneau** [comment]
Hi Conal, Working from home today and just took the liberty of closing this issue because from my exploration of the viz on Friday it looks like you've achieved this task. Hope you're okay with this?
On gmail today. Cheers
