### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#9]
I flagged some time ago in an email the critical need for PROV to 
1. be able to measure visits to the PROVisualizer page using Google Analytics. We will need you to create and embed the Google tracking code into the PROVisualizer page so that we can add it to our Google Analytics account.
2. be able to ,measure number of Triplestore queries (from the server log?), so we will need you to add guidance around to access this measure in the Write Deployment Guide  #4 task please.

**Comment by asaletourneau** [comment]
I just realized that PROV (i.e. me) will need to create the Google Analytics tracking code snippet using our existing Account and that we will copy and paste the snippet directly into the PROVisualizer webpage 'immediately before the closing </head> tag.' as advised here https://support.google.com/analytics/answer/1008080?hl=en 
This means that we will only need you to execute dotpoint 2 above.

**Comment by Conal-Tuohy** [comment]
Suggest use of Apache web server log to track access to the CSV files. This will work no matter where the visualization is embedded.

**Comment by asaletourneau** [comment]
Are you able to include in the Deployment Guide  #4 this recommendation please and how to actually do this. Kaz may indeed know how but for the unitiated such as myself it would be great to have it speled out in black and white :)

**Comment by Conal-Tuohy** [comment]
added in e150130e49cb2128f9c8f0faeaa1b3df54cb81be
